"""Application contracts; unsupported or unverified operations are explicit."""
from datetime import date
from typing import Protocol,Any
class ProviderError(RuntimeError):
    def __init__(self,code="PROVIDER_UNAVAILABLE",retry_after=None):
        super().__init__(code);self.code=code;self.retry_after=retry_after
class WriteDisabled(ProviderError):
    def __init__(self):super().__init__("WRITE_DISABLED")
class ReadProvider(Protocol):
    name:str
    async def get_accounts(self)->list[dict[str,Any]]:...
    async def get_campaigns(self,account_id:str,start:date,end:date)->list[dict[str,Any]]:...
    async def get_adsets(self,account_id:str,start:date,end:date)->list[dict[str,Any]]:...
    async def get_ads(self,account_id:str,start:date,end:date)->list[dict[str,Any]]:...
    async def get_creatives(self,account_id:str,start:date,end:date)->list[dict[str,Any]]:...
    async def get_insights(self,account_id:str,start:date,end:date,level:str="ad")->dict[str,Any]:...
    async def get_entity_state(self,account_id:str,kind:str,entity_id:str)->dict[str,Any]:...
    def get_capabilities(self)->dict[str,Any]:...
    async def health_check(self)->dict[str,Any]:...
    async def close(self):...

class DisabledWriteContract:
    async def pause_entity(self,*args,**kwargs):raise WriteDisabled()
    async def enable_entity(self,*args,**kwargs):raise WriteDisabled()
    async def set_budget(self,*args,**kwargs):raise WriteDisabled()
    async def set_bid(self,*args,**kwargs):raise WriteDisabled()

class ActionProviderRouter:
    """Future Action Engine boundary. Never retry/fail over an unknown WRITE."""
    def route(self,*args,**kwargs):raise WriteDisabled()
    async def execute(self,*args,**kwargs):raise WriteDisabled()
